name       : yquake2
version    : '7.30'
release    : 4
source     :
    - https://github.com/yquake2/yquake2/archive/QUAKE2_7_30.tar.gz : e041c00072b1e447d0b138be40a1b61e015deda7191721038a100621d1b89d61
license    : GPL-2.0-or-later
component  : games.action
summary    : This is the Yamagi Quake II Client, an enhanced version of id Software's Quake II with focus on offline and coop gameplay
description: |
    This is the Yamagi Quake II Client, an enhanced version of id Software's Quake II with focus on offline and coop gameplay.
    Game data must be placed in ~/.yq2/baseq2.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
setup      : |
    %cmake -DSYSTEMWIDE_SUPPORT=1 \
           -DWITH_SYSTEMDIR=/usr/share/yquake2 \
           .
build      : |
    %make
install    : |
    install -Dm00755 release/quake2 $installdir/usr/share/yquake2/quake2
    install -Dm00755 release/q2ded $installdir/usr/share/yquake2/q2ded
    install -Dm00644 release/baseq2/game.so $installdir/usr/share/yquake2/baseq2/game.so
    install -Dm00644 release/ref_soft.so $installdir/usr/share/yquake2/ref_soft.so
    install -Dm00644 release/ref_gl1.so $installdir/usr/share/yquake2/ref_gl1.so
    install -Dm00644 release/ref_gl3.so $installdir/usr/share/yquake2/ref_gl3.so
    install -Dm00644 stuff/icon/Quake2.png $installdir/usr/share/pixmaps/yquake2.png
    install -Dm00644 $pkgfiles/yquake2.desktop $installdir/usr/share/applications/yquake2.desktop
