name       : yquake2
version    : '6.00'
release    : 2
source     :
    - https://github.com/yquake2/yquake2/archive/QUAKE2_6_00.tar.gz : 57f8c2abd11a63b418620a32fabd7bc32b545b4461fc8c848815a150879600a7
license    : GPL-2.0
component  : games.action
summary    : This is the Yamagi Quake II Client, an enhanced version of id Software's Quake II with focus on offline and coop gameplay
description: |
    This is the Yamagi Quake II Client, an enhanced version of id Software's Quake II with focus on offline and coop gameplay
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(vorbis)
setup      : |
    %cmake -DSYSTEMWIDE_SUPPORT=1 \
           -DWITH_SYSTEMDIR=/usr/share/yquake2 \
           .
build      : |
    %make
install    : |
    install -D -m 00755 release/quake2 $installdir/usr/share/yquake2/quake2
    install -D -m 00755 release/q2ded $installdir/usr/share/yquake2/q2ded
    install -D -m 00644 release/baseq2/game.so $installdir/usr/share/yquake2/baseq2/game.so
    install -D -m 00644 stuff/icon/Quake2.png $installdir/usr/share/pixmaps/yquake2.png
    install -D -m 00644 $pkgfiles/yquake2.desktop $installdir/usr/share/applications/yquake2.desktop
