name       : yquake2
version    : '7.42'
release    : 9
source     :
    - https://github.com/yquake2/yquake2/archive/QUAKE2_7_42.tar.gz : 2bb17efe6d626e781cc70cb3abc44386d8a48ee8eea0027a0a4060118d64bdba
license    : GPL-2.0-or-later
component  : games.action
homepage   : https://www.yamagi.org/quake2/
summary    : This is the Yamagi Quake II Client, an enhanced version of id Software's Quake II with focus on offline and coop gameplay
description: |
    This is the Yamagi Quake II Client, an enhanced version of id Software's Quake II with focus on offline and coop gameplay.
    Game data must be placed in ~/.yq2/baseq2.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libcurl)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
rundeps    :
    - openal-soft
setup      : |
    %cmake . -DSYSTEMWIDE_SUPPORT=ON
build      : |
    %make
install    : |
    install -Dm00755 release/quake2 $installdir/usr/share/yquake2/quake2
    install -Dm00755 release/q2ded $installdir/usr/share/yquake2/q2ded
    install -Dm00644 release/baseq2/game.so $installdir/usr/share/yquake2/baseq2/game.so
    install -Dm00644 release/ref_soft.so $installdir/usr/share/yquake2/ref_soft.so
    install -Dm00644 release/ref_gl1.so $installdir/usr/share/yquake2/ref_gl1.so
    install -Dm00644 release/ref_gl3.so $installdir/usr/share/yquake2/ref_gl3.so
    install -Dm00644 stuff/icon/Quake2.png $installdir/usr/share/pixmaps/yquake2.png
    install -Dm00644 $pkgfiles/yquake2.desktop $installdir/usr/share/applications/yquake2.desktop

    install -dm00755 $installdir/usr/bin
    ln -s /usr/share/yquake2/quake2 $installdir/usr/bin/quake2
    ln -s /usr/share/yquake2/q2ded $installdir/usr/bin/q2ded